//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.14 at 02:38:24 AM IST 
//


package org.sds.wsdemo.soap.apis.dtos.multiply.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="intA" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="intB" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "intA",
    "intB"
})
@XmlRootElement(name = "Multiply")
public class Multiply {

    @XmlElement(required = true)
    protected String intA;
    @XmlElement(required = true)
    protected String intB;

    /**
     * Gets the value of the intA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntA() {
        return intA;
    }

    /**
     * Sets the value of the intA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntA(String value) {
        this.intA = value;
    }

    /**
     * Gets the value of the intB property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntB() {
        return intB;
    }

    /**
     * Sets the value of the intB property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntB(String value) {
        this.intB = value;
    }

}
